platformName: ios

platformVersion: 12.1

deviceName: chaotests
udid: ba46042b307de9e7bd14f8e7f439c6c774f1154c

app: de.bmw.connected.cn
noReset: False

automationName: XCUITest
useNewWDA: false
commandTimeouts: 35000
newCommandTimeout: 1000

#ip: 127.0.0.1
ip: 10.10.100.121
port: 4723
